config/routes.rb
Rails.application.routes.draw do
	
get 'books/new'

root 'root#top'
    post 'books' => 'books#create'
    get 'books' => 'books#index'
    get 'books/:id' => 'books#show', as: 'book'
    get 'books/:id/edit' => 'books#edit', as: 'edit_book' 
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  	@book = Book.new
  end

  def create
    @books = Book.all 
    # ストロングパラメーターを使用
     @book = Book.new(book_params)
    # DBへ保存する
    if  @book.save
    # トップ画面へリダイレクト
    redirect_to book_path(@book.id), notice:"Book was successfully created."
    else
      render 'books/index'
   end
  end

    def index
         @books = Book.all 
         @book = Book.new
    end

    def show
        @book = Book.find(params[:id]) 
    end

    def edit
        @book = Book.find(params[:id])
        
    end

    def update
    	book = Book.find(params[:id])
        book.update(book_params)
        redirect_to book_path(book.id), notice:"Book was successfully created."
    end

    def destroy
    	book = Book.find(params[:id]) #データ(レコード)を1件取得
        book.destroy #データ（レコード）を削除
        redirect_to books_path #List一覧画面へリダイレクト
    end

    private
   
    def book_params
        params.require(:book).permit(:title, :body)
    end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def top 
 
  end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  def new
  	@book = Book.new
  end

  def create
        # ストロングパラメーターを使用
         book = Book.new(book_params)
        # DBへ保存する
         book.save
        # トップ画面へリダイレクト
        redirect_to '/top'
    end

    def show
    	@book = Book.find(params[:id])
    end

    private
   
    def book_params
        params.require(:book).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Body</h4>
    <%= f.text_area :body %>
   <p>
    <%= f.submit 'Update Book' %>  </p>

<% end %>

<%= link_to "show",book_path(@book.id) %>
|
<%= link_to "Back",books_path %>

app/views/books/index.html.erb
<div class="main">

<h3 class="title">Books</h3>

<table>
	<thead>
		<tr>
			<th class="you">Title</th>
			<th class="me">Body</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
		<tr>
		<td>
			<%= book.title %>
		</td>
		<td>
			<%= book.body %>
		</td>
		<td class="for">
			<%= link_to "Show", book_path(book.id), class: "aaa" %>
			<%= link_to "Edit", edit_book_path(book.id), class: "bbb"  %>
			<%= link_to "Destroy",destroy_book_path(book.id), class: "ccc" ,method: :delete,"data-confirm" => "Are you sure？" %>
		</td>
	</tr>
	<% end %>
</tbody>
</table>


<div>
	<h3 class="new">New book</h3>
<!-- form_for部分 -->
<%= form_for @book do |f| %>

 <% if @book.errors.any? %>
    <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

    <h4>Title</h4>
    <%= f.text_field :title %>
 
    <h4>Body</h4>
    <%= f.text_area :body %>
 
    <p><%= f.submit 'Create Book' %></p>
 
</div>

<% end %>

</div>

app/views/books/new.html.erb
<div>
	<h1>新規投稿</h1>
<!-- form_for部分 -->
<%= form_for(@book, url: '/books') do |f| %>
 
    <h4>タイトル</h4>
    <%= f.text_field :title %>
 
    <h4>本文</h4>
    <%= f.text_area :body %>
 
    <%= f.submit '投稿' %>
 
</div>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p class="green"><%= flash[:notice] %></p>
<% end %>

<div class="mainn">

<p><strong>Title:</strong><%= @book.title %></p>
<br>
<br>

<p><strong>Body:</strong>
<%= @book.body %> </p>
<br>
<br>



<%= link_to "Edit", edit_book_path(@book.id) %> 
|<a class="back" href="/books"> Back</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/root/top.html.erb
<h1 class="top">ようこそ　Bookersへ！</h1>
<p class="topp">Bookers では、さまざまな書籍に関するあなたの意見や</p>
<p class="toppp">印象を共有し交換することができます</p>


<p>
<ul>
	<li class="star"><%= link_to "start", :books %></li>
</ul>
</p>